services:

  #FRONTEND
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - gameRecord-network

  #BACKEND
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - gameRecord-network

  #DATABASE
  database:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - gameRecord-network
    volumes:
      - postgres-data:/var/lib/postgresql

  #PGAdmin
  pgadmin:
    image: dpage/pgadmin4:9.15
    restart: unless-stopped
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - gameRecord-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database

networks:
  gameRecord-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data: